//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboticsToolData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvalidHardwareOnly
    {
        public int Id { get; set; }
        public string CTN { get; set; }
        public string AccountName { get; set; }
        public string BAN { get; set; }
        public string NTLogin { get; set; }
        public string SalesManager { get; set; }
        public string HardwareBrand { get; set; }
        public string HardwareVariant { get; set; }
        public Nullable<decimal> HardwareSLP { get; set; }
        public Nullable<decimal> HardwareCharge { get; set; }
        public string SimCardRequired { get; set; }
        public string SimCardSize { get; set; }
        public string HardwareColourVariant { get; set; }
        public string AccessoryDescription { get; set; }
        public Nullable<decimal> AccessoryCost { get; set; }
        public string ChargingAccountHardwareORAirtime { get; set; }
        public string DeliveryAddress { get; set; }
        public string DeliveryType { get; set; }
        public Nullable<decimal> DeliveryCharge { get; set; }
        public string AdditionalComments { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<bool> IsManualProcessed { get; set; }
        public string FileName { get; set; }
        public Nullable<int> ReferenceNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ConnectionType { get; set; }
        public Nullable<System.DateTime> Subscription { get; set; }
        public string HardwareSKUCode { get; set; }
        public string AccessorySKU { get; set; }
        public string AccessoryVariant { get; set; }
        public string SimCardSKUCode { get; set; }
        public string ExistingSIMNo { get; set; }
        public Nullable<bool> IsProcess { get; set; }
    }
}
